-- Missões extra (aditivo): cola no SQL Editor e corre. NÃO apaga nada.
-- Junta 30 missões novas ao baralho para os dias 2 e 3.

insert into missions (text, points, difficulty, active) values
  ('Consegue que alguém te explique o que é a medicina nuclear.', 10, 1, true),
  ('Faz com que alguém diga «isto na Alemanha não era assim».', 15, 2, true),
  ('Consegue que alguém elogie uma peça de roupa tua sem tu pedires.', 15, 2, true),
  ('Faz com que alguém proponha jogar às cartas.', 10, 1, true),
  ('Consegue que alguém conte uma história das férias em Esposende ou na Azurara.', 10, 1, true),
  ('Convence alguém de que houve um episódio nas férias de Islantilha que nunca aconteceu.', 20, 3, true),
  ('Consegue que alguém diga «o mercado imobiliário está impossível».', 15, 2, true),
  ('Faz com que alguém te explique uma regra do ciclismo.', 10, 1, true),
  ('Consegue que alguém admita que nunca viu um jogo do Real Madrid até ao fim.', 15, 2, true),
  ('Faz com que alguém diga «isso é da idade».', 15, 2, true),
  ('Consegue que duas pessoas façam um high-five por algo que tu inventaste celebrar.', 15, 2, true),
  ('Faz com que alguém cheire um copo de vinho e comente o aroma com ar sério.', 10, 1, true),
  ('Consegue que alguém diga «já não se fazem férias como antigamente».', 15, 2, true),
  ('Faz com que alguém confesse qual foi a última coisa que comprou online.', 10, 1, true),
  ('Consegue que alguém te conte um podre de outra pessoa presente.', 20, 3, true),
  ('Faz com que alguém diga o nome de três praias do Norte de seguida.', 10, 1, true),
  ('Consegue que alguém se levante para imitar uma jogada de futebol.', 15, 2, true),
  ('Consegue que alguém te empreste um carregador sem lhe dizeres porquê.', 10, 1, true),
  ('Convence alguém de que o Gerês tem lobos à solta perto da casa.', 15, 2, true),
  ('Consegue que alguém mostre uma foto antiga do grupo no telemóvel.', 15, 2, true),
  ('Faz com que alguém te sirva a sobremesa primeiro que aos outros.', 15, 2, true),
  ('Faz com que alguém reclame do wifi da casa antes de ti.', 10, 1, true),
  ('Consegue que alguém aceite trocar de lugar à mesa contigo com um pretexto inventado.', 15, 2, true),
  ('Faz com que alguém diga «recursos humanos» numa conversa que não é de trabalho.', 15, 2, true),
  ('Consegue que alguém desenhe o logótipo de uma marca de memória.', 15, 2, true),
  ('Faz com que alguém conte quanto custou uma coisa cara que comprou.', 15, 2, true),
  ('Consegue que três pessoas diferentes te digam as horas em 10 minutos.', 20, 3, true),
  ('Consegue que alguém segure no teu copo enquanto inventas que tens de fazer outra coisa.', 10, 1, true),
  ('Faz com que alguém proponha ir ver o pôr do sol.', 15, 2, true),
  ('Consegue que alguém te chame «chef» sem seres tu a pedir.', 15, 2, true);
