-- Missões v2 (aditivo): 36 novas — engenharia social, teatro, triggers frescos, meta.
-- Cola no SQL Editor e corre. NÃO apaga nada.

insert into missions (text, points, difficulty, active) values
  ('Conta um «segredo» inofensivo a uma pessoa e consegue que ele te volte aos ouvidos por uma terceira.', 20, 3, true),
  ('Consegue que outra pessoa anuncie ao grupo uma ideia que tu lhe plantaste a sós.', 20, 3, true),
  ('Consegue que alguém te convide para uma atividade que tu próprio sugeriste primeiro a uma terceira pessoa.', 20, 3, true),
  ('Convence alguém a trocar de lugar «porque ali se está melhor» — e fica tu com o lugar.', 15, 2, true),
  ('Consegue que alguém defenda com convicção uma opinião que tu lhe «emprestaste» horas antes.', 20, 3, true),
  ('Faz com que duas pessoas se cumprimentem com um aperto de mão formal, sem lho pedires diretamente.', 20, 3, true),
  ('Consegue que alguém vá verificar se deixou alguma coisa ligada ou aberta, sem motivo nenhum.', 15, 2, true),
  ('Faz com que o grupo tire uma fotografia de grupo hoje — e fica tu no centro.', 15, 2, true),
  ('Consegue que alguém ponha a tocar uma música que tu escolheste antes, sem lha pedires.', 15, 2, true),
  ('Convence duas pessoas de que já se tinham cruzado numa ocasião que nunca aconteceu.', 20, 3, true),
  ('Consegue que alguém te guarde comida «para não ficares sem», sem tu pedires.', 15, 2, true),
  ('Muda um objeto de sítio e consegue que o dono pergunte em voz alta quem lho tirou. Devolve depois.', 15, 2, true),
  ('Consegue que alguém te ofereça o lugar do pendura na próxima ida de carro.', 10, 1, true),
  ('Faz com que duas pessoas apostem alguma coisa entre elas — tu és só a «testemunha».', 15, 2, true),
  ('Consegue que alguém proponha ao grupo um plano para amanhã que tu desenhaste por interposta pessoa.', 20, 3, true),
  ('Atende uma chamada fingida e mantém a conversa 2 minutos à frente de pelo menos 3 pessoas.', 15, 2, true),
  ('Janta do princípio ao fim com os talheres nas mãos trocadas, sem ninguém comentar.', 10, 1, true),
  ('Inventa uma «tradição do Gerês» e executa-a com ar sério até duas pessoas participarem.', 20, 3, true),
  ('Finge que perdeste algo importante, mobiliza duas pessoas para procurar — e «encontra-o» no teu bolso.', 15, 2, true),
  ('Passa 15 minutos a responder a tudo só com perguntas, sem ninguém topar.', 15, 2, true),
  ('Adota um tique novo (ex.: estalar os dedos antes de falar) até alguém o imitar sem reparar.', 20, 3, true),
  ('A meio de uma refeição, faz um discurso de agradecimento solene como se fosse um casamento.', 10, 1, true),
  ('Reage com emoção desmedida a uma coisa banal (um legume, uma pedra) e aguenta a personagem até alguém se rir.', 10, 1, true),
  ('Comporta-te de forma subtilmente estranha até alguém te perguntar «estás bem?» três vezes no mesmo dia.', 15, 2, true),
  ('Consegue que alguém diga «isso dava um momento para a app».', 15, 2, true),
  ('Faz com que alguém te conte um sonho que teve (de dormir, não de vida).', 10, 1, true),
  ('Consegue que alguém diga «no meu tempo é que era» ou «os miúdos de hoje…».', 10, 1, true),
  ('Faz com que alguém admita em voz alta que está viciado na app.', 10, 1, true),
  ('Consegue que alguém pergunte quanto custou a casa do fim de semana.', 10, 1, true),
  ('Faz com que alguém descreva ao grupo um cheiro («cheira a quê?») que tu criaste ou inventaste.', 15, 2, true),
  ('Consegue que duas pessoas discutam com convicção sobre o nome de uma estrela ou constelação — à noite, no jardim.', 20, 3, true),
  ('Faz com que alguém proponha ir todos ver o nascer do sol (não precisa de acontecer).', 15, 2, true),
  ('Acusa alguém de uma missão que TU tens na mão.', 10, 1, true),
  ('Consegue que alguém te mostre as missões dele de livre vontade.', 20, 3, true),
  ('Provoca uma acusação errada contra ti hoje.', 20, 3, true),
  ('Convence um colega de equipa a reclamar uma missão dele ao mesmo tempo que tu, para dividir o Tribunal.', 15, 2, true);
